### PR TITLE
Closes #748. Pad the injector pod durations so they usually complete …

### LINKED ISSUE #748: 7.26.0 Upgrade Issues - InjectionStatus PreviouslyPartiallyInjected
**Describe the bug**
Hi team, We recently tried to upgrade from version 7.13.1 to 7.26 and we are facing issues trying to achieve the same behaviour. We previously reached out to you about [issues with dynamic targeting](https://github.com/DataDog/chaos-controller/issues/744), we upgraded to your newest release and we are hoping to get some further guidance.
We wanted to understand the expected behaviour of the Injection status. For example, when running cpu pressure, the final status ends up being PreviouslyPartiallyInjected despite the experiment injecting all the desired pods. 

**To Reproduce**

1. This is an example of a cpu-pressure experiment
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: cpu-pressure-pod-rohab
  namespace: chaos-engineering-framework
  annotations:
    chaos.datadoghq.com/environment: dev
spec:
  level: pod
  duration: 6m
  selector:
    app.kubernetes.io/name: "fault-injection-showcase"
    app: "fault-injection-showcase--plugin-master"
  count: 100%
  staticTargeting: true
  cpuPressure: 
    count: 100%
```
The cpu pressure correctly identify targets and injects the failure. We believe the logs attached below for cpu-pressure show that the targeted pods are not seen as ready and later go into a terminated state 
Flow:
1.Disruption Created
2. 2 Tagets identified
3. 2 chaos pods created.
4. No Status straight to "PartiallyInjected"
5. 0 pods ready, desired 2
6. 1 chaos pod ready, desired is 2. Status "PartiallyInjected"
7. 2 chaos pods ready, desired is 2. Status "Injected"
8. 1 Chaos pod goes in to a not Ready status
9. 1 chaos pod ready, desired is 2. Status "PartiallyInjected" from "Injected"
10, Error:
```
"caller": "controllers/disruption_controller.go:148",
  "message": "a retryable error occurred in reconcile loop",
  "disruptionName": "cpu-pressure-pod-rohab",
  "disruptionNamespace": "chaos-engineering-framework",
  "error": "error handling chaos pods termination: Operation cannot be fulfilled on disruptions.chaos.datadoghq.com \"cpu-pressure-pod-rohab\": the object has been modified; please apply your changes to the latest version and try again"
```
11. 0 chaos pod ready, desired is 2, Termination 1 Status "PartiallyInjected" from "PausedPartiallyInjected"
12. 0 chaos pod ready, desired is 2, Termination 2 Status "PausedPartiallyInjected" from "PreviouslyPartiallyInjected"

**Expected behavior**
We expect the experiment to finish on PreviouslyInjected if all the desired pods are injected.

**Logs**
[chaos-controller-27-06.txt](https://github.com/DataDog/chaos-controller/files/12185506/chaos-controller-27-06.txt)
[cpu_pressure_partially_injection_debug_chaos_pod_log.txt](https://github.com/DataDog/chaos-controller/files/12185507/cpu_pressure_partially_injection_debug_chaos_pod_log.txt)

Describe on pods on cpu pressure(from a different experiment time but same experiment manifest)
[injector_pod_describe.txt](https://github.com/DataDog/chaos-controller/files/12185558/injector_pod_describe.txt)
[target_pod_describe.txt](https://github.com/DataDog/chaos-controller/files/12185559/target_pod_describe.txt)

If you have any ideas. please let us know. 

**Environment:**
Kubernetes version: v1.24.15-eks-a5565ad
Controller version: 7.26.0
Cloud provider (or local): AWS EKS
Base OS for Kubernetes: Amazon Linux: 5.4.242-156.349.amzn2.x86_64

### PR DESCRIPTION
**Pull request by ptnapoleon**
…later than the chaos-controller

## What does this PR do?

- [ ] Adds new functionality
- [ ] Alters existing functionality
- [ ] Fixes a bug
- [ ] Improves documentation or testing

Please briefly describe your changes as well as the motivation behind them:
- Pad the duration of the injector pods by two seconds to "usually" eliminate the case where the injectors stop <1 second prior to the chaos-controller expecting them to, resulting in status abnormalities such as #748. 
- After testing in our staging env, this seems to have no adverse effects. It should help mitigate #748

## Code Quality Checklist

- [ ] The documentation is up to date.
- [ ] My code is sufficiently commented and passes continuous integration checks.
- [ ] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md)).

## Testing

- [ ] I leveraged continuous integration testing
    - [ ] by depending on existing `unit` tests or `end-to-end` tests.
    - [ ] by adding new `unit` tests or `end-to-end` tests.
- [ ] I manually tested the following steps:
    - `x`
    - [ ] locally.
    - [ ] as a canary deployment to a cluster.

### CODE REVIEW

File: services/chaospod.go [hunk 1]
```diff
@@ -278,8 +278,11 @@ func (m *chaosPodService) GenerateChaosPodOfDisruption(disruption *chaosv1beta1.
 	// to give time for cleaning
 	activeDeadlineSeconds := int64(disruption.RemainingDuration().Seconds()) + 10
 
+	// It can cause abnormalities in the status of a Disruption if injector pods consider themselves complete in the ~second before the chaos-controller believes the disruption is complete.
+	// To avoid making our termination state machine logic more complicated, we will pad the injector pod duration by two seconds.
+	// See https://github.com/DataDog/chaos-controller/issues/748
 	args = append(args,
-		"--deadline", time.Now().Add(disruption.RemainingDuration()).Format(time.RFC3339))
+		"--deadline", time.Now().Add(time.Second*2).Add(disruption.RemainingDuration()).Format(time.RFC3339))
```
Comment (aymericDD) [inline services/chaospod.go:285]: nit: maybe we can define the time.Second*2 inside a `PadDuration` in order to help understand this extra time?

**Review by aymericDD — DISMISSED** [review]

**Comment by ptnapoleon** [comment]
Definitely don't merge this for now, I'm seeing stuck on removal problems with #764 that this will only exacerbate

**Review by Azoam — APPROVED** [review]

**Review by aymericDD — APPROVED** [review]
LGTM 👍
